
export const sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "Pack my box with five dozen liquor jugs.",
    "How vexingly quick daft zebras jump.",
    "A wizard's job is to vex chumps quickly in fog.",
    "Few black taxis drive up major quays.",
    "Sphinx of black quartz, judge my vow.",
    "Jackdaws love my big sphinx of quartz.",
    "The five boxing wizards jump quickly.",
    "Glib jocks quiz nymph to vex dwarf.",
    "Waltz, bad nymph, for quick jigs vex.",
    "Quick-gaited zebras vexed my lazy wolf-dog.",
    "Two driven jocks help fax my big quiz.",
    "The hungry purple hippo quickly jumped over the lazy dog.",
    "Sympathizing would fix Quaker objectives.",
    "A very big box of chocolates was quickly given to the judges.",
    "By Jove, my quick study of lexicography won a prize.",
    "Crazy Fredericka bought many very exquisite opal jewels.",
    "We promptly judged antique ivory buckles for the next prize.",
    "Jaded zombies acted quaintly but kept driving their oxen forward.",
    "The job of waxing linoleum frequently peeves my knights.",
    "My girl wove six dozen plaid jackets before she quit.",
    "A quick movement of the enemy will jeopardize six gunboats.",
    "All questions asked by five watch experts amazed the judge.",
    "The wizard quickly jinxed the gnomes before they vaporized.",
    "Brown jars prevented the mixture from freezing too quickly.",
    "Public junk dwarves quiz paradoxical elves.",
    "Six crazy kings vowed to abolish my pitiful jousts.",
    "How quickly daft jumping zebras vex.",
    "Fix problem quickly with galvanized jets.",
    "Go, lazy fat vixen; be shrewd, jump quick.",
    "When zombies arrive, quickly fax Judge Pat.",
    "Heavy boxes perform quick waltzes and jigs.",
    "A very bad quack might jinx zippy fowls.",
    "My faxed joke won a pager in the cable TV quiz show.",
    "Five or six big jet planes zoomed quickly by the new tower.",
    "Exploring the zoo, we saw every kangaroo jump and quail.",
    "Lazy movers quit their job.",
    "Six big devils from Japan quickly forgot how to waltz.",
    "Why shouldn't a quick diplomat vex the judge?",
    "Verbatim reports were quickly given by the amazed expert.",
    "Foxy parsons quiz and cajole the lovelorn vamp.",
    "The jay, pig, fox, zebra and my wolves quack!",
    "A mad boxer shot a quick, gloved jab to the jaw of his dizzy opponent.",
    "Just keep examining every low bid quoted for zinc etchings.",
    "The exodus of jazzy pigeons varying in size and quality is funky.",
    "We have just quoted on nine dozen boxes of gray lamp wicks.",
    "A large fawn jumped quickly over white zinc boxes.",
    "Big Fuji hawks vexed Jack with their noisy squawking.",
    "The quick onyx goblin jumps over the lazy dwarf.",
    "Five jumbo jets are circling the city, waiting for the go-ahead to land.",
    "Back in my quaint garden, jaunty zinnias vie with flaunting phlox.",
    "Puzzled women bequeath jerks very exotic gifts.",
    "Just work on solving this quiz problem with five given equations.",
    "Viewing quizzical abstracts mixed up hefty jocks.",
    "Playing jazz vibe chords quickly excites my wife.",
    "A quick brown fox might jump on a lazy dog.",
    "Fickle jinx bog dwarves spy math quiz.",
    "My kind zap frog waved hi.",
    "Zany Jacques won top prize for his flexible acrobatics.",
    "Mr. Jock, TV quiz PhD, bags few lynx.",
    "Blowzy night-frumps vex'd Jack Q.",
    "Five quacking zephyrs jolt my wax bed.",
    "The quick-witted judge questioned the veracity of the alibi.",
    "Two hardy boxing kangaroos jet-propelled themselves forward.",
    "Grumpy wizards make toxic brew for the evil Queen and Jack.",
    "For only $49, you can purchase this amazing jigsaw puzzle of a quaint valley.",
    "Have a pick: twenty-six letters — no forcing a jumbled quiz!",
    "We want to pick five vexing quiz questions for next week's show.",
    "Amazingly few discotheques provide jukeboxes.",
    "No kidding, drunken crawfish in back kitchens jig."
];
